(defconst nord-colors '((aurora-0 . "#bf616a")
                        (aurora-1 . "#d08770")
                        (aurora-2 . "#ebcb8b")
                        (aurora-3 . "#a3be8c")
                        (aurora-4 . "#b48ead")
                        (frost-0 . "#8fbcbb")
                        (frost-1 . "#88c0d0")
                        (frost-2 . "#81a1c1")
                        (frost-3 . "#5e81ac")
                        (nord0 . "#2e3440")
                        (nord1 . "#3b4252")
                        (nord2 . "#434c5e")
                        (nord3 . "#4c566a")
                        (nord4 . "#d8dee9")
                        (nord5 . "#e5e9f0")
                        (nord6 . "#eceff4")
                        (nord7 . "#8fbcbb")
                        (nord8 . "#88c0d0")
                        (nord9 . "#81a1c1")
                        (nord10 . "#5e81ac")
                        (nord11 . "#bf616a")
                        (nord12 . "#d08770")
                        (nord13 . "#ebcb8b")
                        (nord14 . "#a3be8c")
                        (nord15 . "#b48ead")
                        (polar-night-0 . "#2e3440")
                        (polar-night-1 . "#3b4252")
                        (polar-night-2 . "#434c5e")
                        (polar-night-3 . "#4c566a")
                        (snow-storm-0 . "#d8dee9")
                        (snow-storm-1 . "#e5e9f0")
                        (snow-storm-2 . "#eceff4")))

(defun nord-color (name)
  (cdr (assoc name nord-colors)))

(defun nano-theme-set-dark-nord ()
  "Apply dark Nano theme base."
  ;; Colors from Nord theme at https://www.nordtheme.com
  (setq frame-background-mode     'dark)
  (setq nano-color-foreground (nord-color 'snow-storm-2))

  (setq nano-color-critical   (nord-color 'aurora-1))
  (setq nano-color-salient    (nord-color 'frost-2))
  (setq nano-color-strong     (nord-color 'aurora-2))
  (setq nano-color-subtle     (nord-color 'polar-night-2))
  (setq nano-color-faded      (nord-color 'frost-2))

  (setq nano-color-background "#212123") ;; darker
  (setq nano-color-popout     (nord-color 'polar-night-1))
  (setq nano-color-highlight  (nord-color 'polar-night-2))

  ;; to allow for toggling of the themes.
  (setq nano-theme-var "dark"))

(provide 'theme-nord)
