(add-to-list 'load-path (concat user-emacs-directory "elisp"))

(require 'base)
(require 'base-completion)
(require 'base-extensions)
(require 'base-global-keys)
(require 'base-shell)
(require 'base-theme)
(require 'base-meow)
(require 'base-llm)

(require 'lang-java)
(require 'lang-markdown)
(require 'lang-python)
(require 'lang-scheme)
